# Generated by Django 5.2.4 on 2025-08-03 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClubLogEntity",
            fields=[
                (
                    "adif",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("prefix", models.CharField(db_index=True, max_length=255)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("cqz", models.IntegerField(db_index=True)),
                ("cont", models.CharField(db_index=True, max_length=255)),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("whitelisted", models.BooleanField(default=True)),
                ("whitelist_start", models.DateTimeField(blank=True, null=True)),
                ("whitelist_end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ClubLog Entity",
                "verbose_name_plural": "ClubLog Entities",
                "ordering": ("adif",),
            },
        ),
        migrations.CreateModel(
            name="ClubLogException",
            fields=[
                (
                    "record",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("call", models.CharField(db_index=True, max_length=255)),
                ("entity", models.CharField(db_index=True, max_length=255)),
                ("adif", models.IntegerField(db_index=True)),
                ("cqz", models.IntegerField(db_index=True)),
                (
                    "cont",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "ClubLog Exception",
                "verbose_name_plural": "ClubLog Exceptions",
                "ordering": ("call",),
            },
        ),
        migrations.CreateModel(
            name="ClubLogInvalidOperation",
            fields=[
                (
                    "record",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("call", models.CharField(db_index=True, max_length=255)),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "ClubLog Zone Invalid Operation",
                "verbose_name_plural": "ClubLog Zone Invalid Operations",
                "ordering": ("call",),
            },
        ),
        migrations.CreateModel(
            name="ClubLogPrefix",
            fields=[
                (
                    "record",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("call", models.CharField(db_index=True, max_length=255)),
                ("entity", models.CharField(db_index=True, max_length=255)),
                ("adif", models.IntegerField(db_index=True)),
                ("cqz", models.IntegerField(db_index=True)),
                ("cont", models.CharField(db_index=True, max_length=255)),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "ClubLog Prefix",
                "verbose_name_plural": "ClubLog Prefixes",
                "ordering": ("call",),
            },
        ),
        migrations.CreateModel(
            name="ClubLogZoneException",
            fields=[
                (
                    "record",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("call", models.CharField(db_index=True, max_length=255)),
                ("zone", models.IntegerField(db_index=True)),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "ClubLog Zone Exception",
                "verbose_name_plural": "ClubLog Zone Exceptions",
                "ordering": ("call",),
            },
        ),
    ]
