# Generated by Django 5.2.4 on 2025-08-03 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="eQSLUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("callsign", models.CharField(db_index=True, max_length=50)),
                ("date_from", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "eQSL User",
                "verbose_name_plural": "eQSL Users",
            },
        ),
        migrations.CreateModel(
            name="LoTWUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("callsign", models.CharField(db_index=True, max_length=50)),
                ("date_from", models.DateTimeField()),
            ],
            options={
                "verbose_name": "LoTW User",
                "verbose_name_plural": "LoTW Users",
            },
        ),
    ]
