# Generated by Django 5.2.4 on 2025-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("callsign", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("state", models.CharField(blank=True, default="", max_length=255)),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Zip"
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("locator", models.CharField(max_length=10)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                (
                    "cq_zone",
                    models.PositiveIntegerField(default=0, verbose_name="CQ Zone"),
                ),
                (
                    "itu_zone",
                    models.PositiveIntegerField(default=0, verbose_name="ITU Zone"),
                ),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "My Station",
                "verbose_name_plural": "My Stations",
            },
        ),
    ]
